### ISSUE TITLE
Не работает в контейнере

### ISSUE THREAD

**Issue by alexunderboots** [drevofil/alertmanager-telegram-webhook#1]
Добрый день, build (latest-ubi), run+debug
На курлы из примера не отвечает (((( в докер-логе новые сообщения не пишутся (((

старые версии не работают на v2 (((

**Comment by alexunderboots** [comment]
Так-же непонятно назначение переменной
appkey

**Comment by drevofil** [comment]
Добрый день, текущая версия [1.13.1-ubi9](https://hub.docker.com/layers/brrra/telegram/1.13.1-ubi9/images/sha256-d469a52351f000d21d3f7af03611997b89f1225e6970a720de7099fe7336c9ac?context=explore) сейчас работает в openshift, поменяю в манифесте k8s.
appkey - переменная SECRET_KEY для flask, для подписи куков [Документация](https://flask.palletsprojects.com/en/2.3.x/config/)
